package be.brkaisin.strava.models

import be.brkaisin.strava.models.PolylineMap.SummaryPolylineMap

import java.time.Instant

case class SummaryActivity(
    id: Long,
    externalId: String,
    uploadId: Long,
    athlete: MetaAthlete,
    name: String,
    distance: Float,
    movingTime: Int,
    elapsedTime: Int,
    totalElevationGain: Float,
    elevHigh: Option[Float],
    elevLow: Option[Float],
    sportType: SportType,
    startDate: Instant,
    startDateLocal: Instant,
    timezone: String,
    startLatlng: Option[LatLng],
    endLatlng: Option[LatLng],
    achievementCount: Int,
    kudosCount: Int,
    commentCount: Int,
    athleteCount: Int,
    photoCount: Int,
    totalPhotoCount: Int,
    map: SummaryPolylineMap,
    trainer: Boolean,
    commute: Boolean,
    manual: Boolean,
    `private`: Boolean,
    flagged: Boolean,
    workoutType: Option[Int],
    uploadIdStr: String,
    averageSpeed: Float,
    maxSpeed: Float,
    hasKudoed: Boolean,
    hideFromHome: Option[Boolean],
    gearId: Option[String],
    kilojoules: Option[Float],
    averageWatts: Option[Float],
    deviceWatts: Option[Boolean],
    maxWatts: Option[Int],
    weightedAverageWatts: Option[Int],
    // fields not described in the Strava API documentation but present in the JSON response
    utcOffset: Option[Int],
    locationCity: Option[String],
    locationState: Option[String],
    locationCountry: Option[String],
    fromAcceptedTag: Option[Boolean],
    averageCadence: Option[Float],
    hasHeartRate: Option[Boolean],
    averageHeartrate: Option[Float],
    maxHeartrate: Option[Float],
    prCounts: Option[Int],
    sufferScore: Option[Int]
)
